channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=23.3.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - numpy==1.24.2
  - packaging==23.0
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.13.0
name: mlflow-env
